### PR TITLE
Enable CI builds

### PR DESCRIPTION
**Pull request by brian-rose**
Following experiments in #10, here I'm setting `execute_notebooks: binder` now that there is a proper environment file in the main branch.

I'm expecting this to fail tests because of the cell with the expected failure.

After verifying that, we'll set the `raises-exception` cell tag and should be good to go.

### CODE REVIEW

**Comment by brian-rose** [comment]
To clarify what's being executed, I stripped all output out of the notebooks.

**Comment by brian-rose** [comment]
Finally have my successful CI failure!

Time to set the cell tag.

**Comment by brian-rose** [comment]
Ok, this runs into a different problem. Sending the notebooks out to execute on the Binder means they don't have access to the bundled data files.

**Comment by brian-rose** [comment]
Ok, this Cookbook now executes itself from start to finish and publishes itself.

**Comment by ThomasMGeo** [comment]
Thanks for all of the work on this @brian-rose ! Looks awesome.

**Pull request merged**
