### PR TITLE
Update to latest template with support for DOI

### PR DESCRIPTION
**Pull request by brian-rose**
This PR should get this repo up to date with the latest changes in the cookbook template.

The DOI links will fail until this gets released and archived on Zenodo. We should make sure that #16 is resolved before cutting a release.

The PR build and preview should show whether #16 is resolved or not.

### CODE REVIEW

**Comment by brian-rose** [comment]
Nope, still getting
```
ModuleNotFoundError: No module named 'ESMF'
```

I'm not sure what's going on. I successfully created the environment and ran the notebooks locally on my Mac laptop.

**Comment by brian-rose** [comment]
The environment was created with `xesmf 0.6.3` but conda-forge apparently has a [version 0.7.1 available](https://github.com/conda-forge/xesmf-feedstock)

**Comment by brian-rose** [comment]
Yep, that did the trick.

There is [actual output in the xESMF notebook](https://projectpythia.org/gridding-cookbook/_preview/17/notebooks/xESMF_introduction.html) now in the preview.

So this PR fixes #16 as well as getting the cookbook ready for release and DOI generation.

@ThomasMGeo take a look! I suggest adding some of your metadata in the CITATION.cff file (ORCID, etc). You can push directly to this PR, or just put stuff in a comment here and I'll update it.

**Comment by brian-rose** [comment]
@ThomasMGeo can you take a look soon and approve this so we can get this cookbook building again?

**Comment by ThomasMGeo** [comment]
Looks great! Thanks. I have an ORCID ([0000-0002-4171-0004](https://orcid.org/0000-0002-4171-0004)) I can add too.

**Pull request merged**
